### ISSUE TITLE
按需加载感觉有点问题

### ISSUE THREAD

**Issue by steel-li** [liamwang/bookist.cc#1]
我引用了Form和FormItem，提示没有找到这个样式，在返回的`ant-design-vue/es/${name}/style`中，如果没有注册FormItem就不生效，注册了就提示找不到样式

**Comment by liamwang** [comment]
fixed: https://github.com/liamwang/bookist.cc/commit/a5dbc7fb361b0c66f30c874b45a7410c081ef765

**Comment by steel-li** [comment]
在按需加载`replaceList`的里面漏了 ```'textarea' : 'input'```

**Comment by liamwang** [comment]
@steel-li 感谢指正，已修复。
